name: EmergencyWhitelist
main: musician101.emergencywhitelist.EmergencyWhitelist
version: '2.0'
description: Secondary whitelisting for server admins.
authors: [Musician101]
maintainer: Musician101
api-version: '1.14'

commands:
    ewl:
      aliases: [ewl]
      description: Simple permissions based whitelisting.
      usage: <command> [help|reload|toggle]

permissions:
   ewl.*:
      default: op
      description: Gives access to all commands.
      children:
         ewl.help: true
         ewl.reload: true
         ewl.toggle: true
         ewl.whitelist: true
   ewl.help:
      default: op
      description: Allows user/group to access the plugin's help command.
   ewl.reload:
      default: op
      description: Allows user/group to access the plugin's reload command.
   ewl.toggle:
      default: op
      description: Allows user/group to toggle the whitelist on or off.
   ewl.whitelist:
      default: op
      description: Whitelists user/group for entry onto the server when the whitelist is enabled.
